hp_template = dict(clustering=dict(
                       atoms_path="path_to_full_class_or_method_list",
                       strategy="sequential",
                       max_iterations=50,
                       min_samples=2,
                       epsilon_step=0.05,
                       include_outliers=False
                    ),
                   analysis=[
                       (
                           "dynamic",
                           dict(
                               atoms_path="path_to_class_or_method_list",
                               features_path="path_to_log_data",
                               epsilon=0.65,
                               similarity="call"
                           )
                       ),
                       (
                           "structural",
                           dict(
                               atoms_path="path_to_class_or_method_list",
                               features_path="path_to_structural_data",
                               epsilon=0.65,
                               similarity="call"
                           )
                       ),
                       (
                           "semantic",
                           dict(
                               atoms_path="path_to_class_or_method_list",
                               features_path="path_to_semantic_data",
                               atoms_tokens="path_to_class_or_method_words",
                               epsilon=0.65,
                               aggregation="mean"
                           )
                       ),
                       (
                           "sum",
                           dict(
                               weights=None,
                               epsilon=0.65,
                           )
                       )
                   ]
)